
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { InspectionRecord } from '../types';

export const generatePDF = (record: InspectionRecord) => {
  const doc = new jsPDF();
  const primaryColor = [220, 38, 38]; // Red-600

  // Header Box
  doc.setFillColor(240, 240, 240);
  doc.rect(0, 0, 210, 40, 'F');
  
  // Title
  doc.setFontSize(22);
  doc.setTextColor(220, 38, 38);
  doc.setFont('helvetica', 'bold');
  doc.text('PRAN RFL GROUP', 105, 15, { align: 'center' });
  
  doc.setFontSize(12);
  doc.setTextColor(100, 100, 100);
  doc.text('FIRE EXTINGUISHER INSPECTION REPORT', 105, 25, { align: 'center' });

  // Metadata Table
  autoTable(doc, {
    startY: 45,
    head: [['Field', 'Information']],
    body: [
      ['Point Number', record.pointNumber],
      ['Section', record.section],
      ['Type', record.extinguisherType],
      ['Month', record.month],
      ['Inspection Date', new Date(record.timestamp).toLocaleDateString()],
      ['Supply Date', record.supplyDate],
      ['Expiry Date', record.expiryDate]
    ],
    theme: 'striped',
    headStyles: { fillColor: primaryColor }
  });

  // Condition Table
  autoTable(doc, {
    startY: (doc as any).lastAutoTable.finalY + 10,
    head: [['Parameter', 'Status']],
    body: [
      ['Seal Status', record.seal],
      ['Pressure Status', record.pressure],
      ['Hose Pipe', record.hosePipe],
      ['Safety Pin', record.safetyPin],
      ['Overall Condition', record.overallCondition || 'No specific issues noted.']
    ],
    theme: 'grid',
    headStyles: { fillColor: [51, 65, 85] } // Slate-700
  });

  // Footer / Signature Section
  const finalY = (doc as any).lastAutoTable.finalY + 15;
  
  doc.setFontSize(10);
  doc.setTextColor(0, 0, 0);
  doc.text('INSPECTED BY:', 15, finalY);
  doc.text(`Name: ${record.fireMarshalName}`, 15, finalY + 7);
  doc.text(`Staff ID: ${record.staffId}`, 15, finalY + 14);

  if (record.signatureData) {
    try {
      doc.addImage(record.signatureData, 'PNG', 150, finalY - 10, 40, 20);
    } catch (e) {
      console.warn("Could not add signature to PDF", e);
    }
  }
  
  doc.setLineWidth(0.5);
  doc.line(145, finalY + 12, 195, finalY + 12);
  doc.text('Authorized Signature', 170, finalY + 18, { align: 'center' });

  // System Footer
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text('Generated by PRAN RFL Digital Inspection App', 105, 285, { align: 'center' });

  doc.save(`PRAN_RFL_Report_${record.pointNumber}_${record.month}.pdf`);
};
